version: '3'

services:

  db:
    image: mysql:5.7
    container_name: mysql-db        
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sampleDB
      MYSQL_USER: sampleUser
    
    ports:
      - "3306:3306"

  web:
    image: php:7.2.2-apache
    container_name: php_web
    dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
